### ISSUE TITLE
Will this run against a simple Com-IP or does it have to be a Texecom Connect unit?

### ISSUE THREAD

**Issue by B-Hartley** [davidMbrooke/texecom-connect#19]
I have a texecom connect unit and a Com-IP.
At the moment, I use the native app against the Texecom Connect and a custom Python to MQTT script against the Com-IP.

It looks like this script is now getting better than my hacked together version (particularly if I can arm/disarm).
But I don't want to lose the backup plan of being able to use the native App.

Thanks,
Bruce.

**Comment by mpredfearn** [comment]
I run it against a Com-WiFi. I'm pretty sure it requires the older protocol spoken by Com-IP and Com-WiFi rather than the texecom Connect which is an entirely different beast that connects to texecoms cloud rather than being a simple UART to IP bridge.

**Comment by B-Hartley** [comment]
ok, thanks.  Last time I tried this script I was running it against by Texecom Connect box.  I'll try it against the Com-IP.  Presumably I need to change the protocol of the Com-IP to the Connect protocol.  At the moment I'm using a script that uses the crestron protocol.
